### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by tropperstyle** [cloudant-labs/hastings#1]
I can't seem to find any documentation on CouchDB 2.0 plugins or how I would install hastings. Any pointers?

Thanks

**Comment by furrycoat21** [comment]
@tropperstyle 

To get CouchDB 2.0 set up with hastings and easton theres a guide here: https://github.com/cloudant-labs/hastings/wiki/Introduce-GeoSpatial-Index-To-CouchDB

In addition to that guide, I had to get the dependencies installed for Easton: 
https://github.com/cloudant-labs/easton/issues/4

Following that I had to adjust the instuctions that the Guide gives for hastings/easton and I had to add easton to the reltool.config in rel/
`{app, easton, [{incl_cond, include}]},`

In addition to that I had to add a Hastings section to the ini file, this may be due to how I'm installing couch though, as I'm overwriting the ini file that it generates
`[hastings] enabled  = true`

At the moment CouchDB 2.0 builds, but is left with this error when I run the Index
`{
"error": "#Port<13667.143580>",
"reason": "{exit_status,127}"
}`

Again, your results may be a little different because of how I'm installing it.

**Comment by furrycoat21** [comment]
One last thing, 

In the section 
> Change on hastings to be compatiable with CouchDB
This is located in the file hastings_index_updater.erl

**Comment by tropperstyle** [comment]
I was able to successful install/run hastings on CouchDB 2.1, so I'll go ahead and close this.

For anyone interested, here is the Dockerfile:

```
FROM debian:8
# Debian dependencies
RUN apt-get update && apt-get upgrade -y && apt-get --no-install-recommends -y install lsb-release build-essential curl git pkg-config libicu-dev libmozjs185-dev libcurl4-openssl-dev ca-certificates

# Erlang
RUN curl -o erlang-solutions.1.0_all.deb https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
RUN dpkg -i erlang-solutions.1.0_all.deb
RUN apt-get update
RUN apt-get install -y esl-erlang=1:19.3.6

# Node
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash
RUN apt-get install -y nodejs

# Rebar
RUN git clone https://github.com/rebar/rebar
RUN cd rebar && make

# Geospatial
RUN curl -sL http://download.osgeo.org/libspatialindex/spatialindex-src-1.8.5.tar.gz | tar xvz
RUN cd spatialindex-src-1.8.5 && ./configure && make && make install
RUN curl -sL http://download.osgeo.org/geos/geos-3.5.1.tar.bz2 | tar vxj
RUN cd geos-3.5.1 && ./configure && make && make install
RUN git clone https://github.com/google/leveldb.git
RUN cd leveldb && make && cp out-static/lib* out-shared/lib* /usr/local/lib/ && cd include/ && cp -r leveldb /usr/local/include/ && ldconfig
RUN apt-get -y install subversion
RUN svn checkout https://svn.osgeo.org/metacrs/csmap/branches/14.01/CsMapDev
RUN cd CsMapDev/Source && make -fLibrary.mak
RUN cd CsMapDev/Dictionaries && make -fCompiler.mak && ./CS_Comp . .
RUN cd CsMapDev/Test && make -fTest.mak && ./CS_Test -d../Dictionaries
RUN cp -r CsMapDev/Include /usr/local/include/CsMap && cp CsMapDev/Source/CsMap.a /usr/local/lib/libCsMap.a && ldconfig

# CouchDB
RUN git clone -b geospatial https://github.com/tropperstyle/couchdb.git
RUN cd couchdb && ./configure --disable-docs && make release

# Single Node setup
COPY data couchdb/rel/couchdb/data

# Docker config adjustments
RUN sed -e 's/^bind_address = .*$/bind_address = 0.0.0.0/' -i couchdb/rel/couchdb/etc/default.ini
RUN sed -e 's!/usr/local/var/log/couchdb/couch.log$!/dev/null!' -i couchdb/rel/couchdb/etc/default.ini
RUN echo "\n[easton]\nenabled = true" >> couchdb/rel/couchdb/etc/default.ini
RUN echo "\n[hastings]\nenabled = true" >> couchdb/rel/couchdb/etc/default.ini

# Start server
CMD couchdb/rel/couchdb/bin/couchdb
EXPOSE 5984
```

My CouchDB fork contains a commit including the changes from the wiki, @furrycoat21, and more.

**Comment by Ravenstine** [comment]
@tropperstyle I ran your Dockerfile and it was the first time I got Hastings(and Easton) to build with CouchDB... however every query returns empty results.  Did you ever get it to geospatially index successfully?

Also, I saw in another issue that you were considering a different approach using geohashes.  I'm curious to know what you came up with in that direction since our use cases might be similar.
